### PR TITLE
Added FormHandler and jsp

### PR DESCRIPTION
**Pull request by Rachelware**
Updating what I changed while working on images 2. Currently uses blobstore on a separate page successfully. Change to UfoDataServlet is just the name to allow compilation.

### CODE REVIEW

**Review by niccireinking — COMMENTED** [review]
If you change UfoDataServlet name, you need to change the class name too

**Review by niccireinking — CHANGES_REQUESTED** [review]
Need to change the class name if you want to change the file name.

**Comment by Rachelware** [comment]
I was getting an error so I tried to change the file name to Ufo, I have now changed it so it actually matches.

**Review by miaboloix — APPROVED** [review]

**Review by Rachelware — COMMENTED** [review]
So this branch now holds 2 ways of image uploading, client-side and server-side. Depending on what we need later, one or the other might work better. Both can be run now using the jsp for server-side and html for client-side. Neither is connected to the message box because of the big changes to the layout and how puzzles will play out.

**Review by niccireinking — APPROVED** [review]

**Pull request merged**
